CHANGELOG.md, Makefile, PROJECT, config/default/agent_image_patch.yaml, config/default/kustomization.yaml, config/default/manager_image_patch.yaml, doc/bgp_config.md
=> 🎉🎉 release v0.1

config/agent/agent.yaml, config/default/agent_image_patch.yaml, config/default/kustomization.yaml, config/default/manager_image_patch.yaml, config/manager/manager.yaml, test/e2e/e2e_test.go, test/e2eutil/test_case.go, test/test-configs/reciever.template
=> 🚒 add passive mode test

.gitignore, pkg/controller/service/finalizer.go, pkg/controller/service/service_controller.go, test/Jenkinsfile, test/e2e/e2e_test.go, test/e2eutil/e2eutil.go, test/e2eutil/log.go, test/e2eutil/test_case.go
related with  #44 #43 
help to locate the problem
=>  🚑 double check service type and add log to jenkinsfile

README.md, README_zh.md
Signed-off-by: 周鹏飞@yunify <pengfeizhou@yunify.com>
=> add Porter intro of English version

Makefile, README.md, README_zh.md, config/release/agent_image_patch.yaml, config/release/manager_image_patch.yaml, doc/bgp_config.md, doc/deploy_baremetal.md, doc/simulate_with_bird.md
=> 📖 fix docs

cmd/manager/main.go, config/dev/agent_image_patch.yaml, config/dev/kustomization.yaml, config/dev/manager_image_patch.yaml, controllers/lb/controller.go, controllers/lb/lb.go, doc/deploy_baremetal.md, pkg/ipam/datastore.go, pkg/ipam/eip_status.go, pkg/ipam/ipam_test.go, pkg/route/gobgp.go, pkg/route/interface.go, pkg/test/bgp_test.go
=> refactor gobgp

api/v1alpha1/eip_types.go, config/crd/bases/network.kubesphere.io_eips.yaml
=> ✨ add validation to crd

doc/simulate_with_bird.md
=> doc: fix the route command

README.md
Signed-off-by: FeynmanZhou <pengfeizhou@yunify.com>
=> refine introduction in README.md

Makefile, controllers/lb/lb.go
1. To find the EIP, look first at the annotations and then at spec.loadBalancerIP #73 
2. `make release` doesn't work under Linux, fixed.
=> Support spec.loadBalancerIP in service

doc/porter-chart.md
Signed-off-by: jian.zhang <jian.zhang@jhlinux.com>
=> add en porter-chart.md && update zh porter-chart.md

doc/compared_with_metallb.md, doc/zh/compared_with_metallb.md
Signed-off-by: Sherlock <sherlockxu@yunify.com>
Update Porter comparison with MetalLB
=> Update Porter comparison with MetalLB

doc/deploy_baremetal.md, doc/eip_config.md, doc/layer2.md, doc/simulate_with_bird.md, doc/usecases.md, doc/zh/bgp_config.md
=> add usecases.md and fix some typos

README.md, doc/usecases.md
remove references to outdated documents from  README.md
=> fix some typo and update README.md

.github/workflows/docker.yml, Dockerfile
Signed-off-by: Zhengyi Lai <zheng1@yunify.com>
=> Add dockerfile && github actions auto push docker image

Dockerfile, deploy/agent/Dockerfile, deploy/manager/Dockerfile, doc/deploy_baremetal.md
Signed-off-by: Zhengyi Lai <zheng1@yunify.com>
=> Add iptables into docker image && clean up docs

Makefile, cmd/agent/Dockerfile, cmd/manager/Dockerfile
=> Support muti arch image

config/workloads/kustomization.yaml, deploy/porter.yaml
=> update install script

README.md, README_zh.md, api/v1alpha1/eip_types.go, config/webhook/service.yaml, config/workloads/manager.yaml, deploy/porter.yaml, doc/bgp_config.md, doc/deploy.md, pkg/manager/generic.go
=> Add param to config webhook port

doc/install-porter-on-kubesphere.md
=> Fixed minor issues.

doc/use-porter-in-layer-2-mode.md
=> Changed the service description.

doc/index.md
=> Written index-en.

pkg/controllers/ipam/ipam.go, pkg/controllers/lb/controller.go
=> filter endpoints not owned by service

doc/how-to-build.md
=> Rewite how-to-build guide

doc/configure-multiple-porter-replicas.md, doc/index.md
=> Written configure-multiple-porter-replicas-en.

doc/how-to-build.md
=> Written how-to-build-en.

doc/install-porter-on-kubesphere.md
=> Added a notice.

doc/install-porter-on-kubesphere.md
=> Added a note.

README.md
=> Redirected links to porterlb.io.

pkg/controllers/lb/controller.go, pkg/speaker/layer2/arp.go
Signed-off-by: Duan Jiong djduanjiong@gmail.com
=> store ip/mac info whether leader or not

README.md
=> Updated README-en.

doc/roadmap.md
=> Roadmap list for Porter

Dockerfile
=> fix the name of the program in the image

ADOPTERS.md, OWNERS, README.md, doc/roadmap.md
Signed-off-by: FeynmanZhou <pengfeizhou@yunify.com>
=> rename porterlb to openelb

api/v1alpha2/eip_types.go, cmd/manager/app/manager.go, pkg/constant/constants.go, pkg/controllers/bgp/bgpconf_controller.go, pkg/controllers/bgp/bgppeer_controller.go, pkg/controllers/bgp/suite_test.go, pkg/controllers/ipam/ipam.go, pkg/controllers/lb/suite_test.go, pkg/manager/generic.go, pkg/util/util.go, pkg/util/util_suite_test.go, pkg/util/util_test.go
=> feat: using cni as speaker sync routes

api/v1alpha2/eip_types.go, cmd/manager/app/manager.go, config/webhook/kustomization.yaml, config/webhook/mutating_webhook.yaml, config/workloads/cert.yaml, deploy/porter.yaml, pkg/constant/constants.go, pkg/controllers/lb/controller.go, pkg/validate/validate.go
Signed-off-by: chaunceyjiang <chaunceyiang@gmail.com>
fix #232 #231
=> eip add default attribute

Makefile, deploy/porter.yaml
Signed-off-by: chaunceyjiang <chaunceyiang@gmail.com>
upgrade openELB version
=> upgrade openELB version

README.md, README_zh.md
Changed:
1. add describe for cncf projectr
2. add chinese README
@zheng1  @FeynmanZhou  PTAL.
=> Update README for cncf project and add chinese README

deploy/openelb.yaml
=> update openelb image version

api/v1alpha2/eip_types.go, cmd/manager/app/manager.go, config/crd/bases/network.kubesphere.io_eips.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml, deploy/openelb.yaml, pkg/constant/constants.go, pkg/controllers/lb/controller.go, pkg/controllers/lb/nodeporxy.go, pkg/leader-elector/election.go, pkg/speaker/vip/keepalived.go, pkg/util/util.go
Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>
fix #245
=> Support non-bgp switch

README.md
=> fix All Contributors badge

.all-contributorsrc, README.md
=> add all contributors

pkg/speaker/vip/keepalived.go
=> fix detect keepalived daemonset

deploy/openelb.yaml
=> update openelb image tag for next version

deploy/uninstall.sh
=> add uninstall script

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
Signed-off-by: Amal Thundiyil <amal.s.thundiyil@gmail.com>
=> ench: add github templates

README.md, README_zh.md
Signed-off-by: renyunkang <renyunkang@kubesphere.io>
fix readme
=> Fix readme file

Makefile, cmd/manager/app/manager.go, pkg/manager/generic.go, pkg/version/version.go
Signed-off-by: renyunkang <renyunkang@kubesphere.io>
Add openelb version info.
```
root@node:~/program/openelb# bin/manager version
{"gitVersion":"v0.5.1","gitCommit":"b327ea42ef12edcbafd30b7b3f952850af02ce3a","gitTreeState":"clean","buildDate":"2022-07-26_17:13:31","goVersion":"go1.16.15","compiler":"g
c","platform":"linux/amd64"}
```
=> Add version info

pkg/controllers/lb/controller.go, pkg/controllers/lb/suite_test.go
Signed-off-by: renyunkang <renyunkang@kubesphere.io>
Fixed openelb exiting abnormally when used by culium or endpoints.subsets.addresses is not specified.
#296
=> allow endpoint nodeName to be empty

pkg/speaker/layer2/arp.go, pkg/speaker/layer2/arp_test.go
Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>
add CIDR range for NICs in layer2
/feature
=> add CIDR range for NICs in layer2

ADOPTERS.md
This is a documentation PR. This fixes the logos for the list of adopters.
=> docs: Fix adopters img link

build/speaker/Dockerfile, cmd/speaker/app/options/options.go, cmd/speaker/app/speaker.go, config/release/kustomization.yaml, config/release/speaker_image_patch.yaml, config/workloads/cert.yaml, config/workloads/kustomization.yaml, config/workloads/speaker.yaml, deploy/openelb.yaml, hack/docker_build.sh, pkg/controllers/bgp/bgpconf_controller.go, pkg/controllers/lb/controller.go, pkg/controllers/lb/eventhandler.go, pkg/log/options.go, pkg/speaker/bgp/path.go, pkg/speaker/bgp/peers.go, pkg/speaker/eip_controller.go, pkg/speaker/layer2/arp_test.go, pkg/speaker/lb_controller.go, pkg/speaker/manager.go, pkg/speaker/speaker.go, pkg/util/util.go
=> refactor openelb bgp speaker

cmd/speaker/app/options/options.go, cmd/speaker/app/speaker.go, config/workloads/speaker.yaml, deploy/openelb.yaml, pkg/constant/constant.go, pkg/speaker/manager.go, pkg/speaker/vip/keepalived.go, pkg/speaker/vip/options.go, pkg/util/util.go
=> refactor openelb vip speaker

.github/workflows/go.yml, Makefile, hack/deploy_openelb.sh, hack/kind_e2e.sh
=> chore: integrate e2e test into the workflow

cmd/manager/app/manager.go, pkg/controllers/ipam/ipam.go, pkg/log/options.go, pkg/manager/generic.go, pkg/speaker/vip/keepalived.go
I just reported issue #354. I checked the code, and this might be a possible implementation.
=> the port of the keepalived process is now configurable

api/v1alpha2/eip_types.go, build/speaker/Dockerfile, cmd/speaker/app/options/options.go, cmd/speaker/app/speaker.go, config/rbac/role.yaml, config/webhook/kustomization.yaml, config/webhook/manifests.yaml, config/workloads/cert.yaml, config/workloads/speaker.yaml, deploy/openelb.yaml, go.mod, go.sum, pkg/constant/constant.go, pkg/controllers/ipam/ipam.go, pkg/controllers/ipam/ipam_test.go, pkg/controllers/lb/controller.go, pkg/speaker/eip_controller.go, pkg/speaker/layer2/announcer.go, pkg/speaker/layer2/arp_announer.go, pkg/speaker/layer2/log.go, pkg/speaker/layer2/memberlist.go, pkg/speaker/layer2/options.go, pkg/speaker/layer2/responder.go, pkg/speaker/lb_controller.go, pkg/speaker/manager.go, pkg/util/util.go
- Refactored layer2 speaker and introduced memberlist to solve the single point of failure and implement failover.
- Fixed some issues with controller IPAM updating service status.
**TODO:**
- Standardize log format.
- More tests for stability.
- Integrate the decision logic of speaker and controller, as they share the same logic.
=> Refactor Layer2 Speaker

Dockerfile
https://github.com/docker-library/golang/issues/502
=> switch to golang:alpine as builder

api/v1alpha2/eip_types.go, cmd/speaker/app/speaker.go, go.mod, go.sum, pkg/constant/constant.go, pkg/speaker/bgp/bgp/path.go, pkg/speaker/eip_controller.go, pkg/speaker/fake.go, pkg/speaker/interface.go, pkg/speaker/layer2/announcer.go, pkg/speaker/layer2/arp_announer.go, pkg/speaker/layer2/memberlist.go, pkg/speaker/lb_controller.go, pkg/speaker/manager.go, pkg/speaker/vip/keepalived.go, pkg/util/iprange/README.md, pkg/util/iprange/parse.go, pkg/util/iprange/parse_test.go, pkg/util/iprange/pool.go, pkg/util/iprange/pool_test.go, pkg/util/iprange/range.go, pkg/util/iprange/range_test.go, pkg/util/util.go
1. add iprange library 
2. refactor speaker
3. optimize ARP announcer
=> refactor speaker

cmd/manager/app/manager.go, go.mod, go.sum, pkg/util/term.go
ref: https://github.com/openelb/openelb/pull/401
=> remove docker dep

charts/values.yaml, deploy/openelb.yaml, hack/generate_manifests.sh
Replace the kubesphere/kube-webhook-certgen image to support the arm64 architecture.
- https://hub.docker.com/r/kubesphere/kube-webhook-certgen/tags
- https://hub.docker.com/r/kubespheredev/kube-webhook-certgen/tags
Update images in helm charts
=> update docker images

pkg/speaker/bgp/bgp/policy.go
=> chore: remove refs to deprecated io/ioutil

CHANGELOG.md, charts/templates/openelb-images-configmap.yaml, charts/templates/openelb-speaker.yaml
update charts & update changelog
=> update charts & update changelog

pkg/util/iprange/parse.go, pkg/util/iprange/parse_test.go, pkg/util/iprange/range_test.go
For OpenELB, all addresses in the created Eip are fully routable. Users should plan the network reasonably before creating an Eip.
fix: https://github.com/openelb/openelb/issues/425
=> fix iprange cidr parsing results

pkg/speaker/manager.go
=> skip existing records when handling service

pkg/speaker/manager.go
Use map to check whether it has been registered. There are hidden dangers in using map's default empty value.
=> determine if the speaker is registered

charts/values.yaml, config/release/manager_image_patch.yaml, config/release/speaker_image_patch.yaml, deploy/openelb.yaml
=> update images tag

.github/workflows/docker.yml
=> update github workflow

README.md, README_zh.md, charts/README.md
o/ you left your old url in the readmes. hope the helm chart isn't load bearing
=> doc fix for old hardcoded github pages url

pkg/controllers/ipam/ipamv6_test.go
=> Add test for IPv6 allocation by IPAM

go.mod, go.sum, pkg/speaker/layer2/announcer.go, pkg/speaker/layer2/arp_announcer.go, pkg/speaker/layer2/const.go, pkg/speaker/layer2/memberlist.go, pkg/speaker/layer2/ndp_announcer.go, pkg/speaker/utils.go, pkg/speaker/vip/keepalived.go
Add NDP announcer to the layer2-speaker so that OpenELB can support IPv6 announcements in layer2 mode
=> Add NDP announcer for layer2-speaker

charts/templates/openelb-controller.yaml
=> remove duplicate entries

pkg/speaker/vip/keepalived.go
fix: can_rach:ipAddress in Keepalived not effective
=> fix: can_rach:ipAddress in Keepalived not effective

.gitignore, pkg/speaker/layer2/arp_announer.go, pkg/speaker/manager.go, pkg/speaker/vip/keepalived.go
/kind/bug
Correct speaker advertisement behavior when service externalTrafficPolicy changes.
https://github.com/openelb/openelb/issues/458
=> Correct speaker advertisement behavior when service externalTrafficPolicy changes.
